### ISSUE TITLE
zenodo files

### ISSUE THREAD

**Issue by wawpaopao** [nanobaselib/NanoBaseLib#2]
I would like to ask if the HEK293T benchmark file in Zenodo contains all the FAST5 information for the three replicates of WT (Wild Type) and the three replicates of (Knock Out)?

**Comment by guangzhaocs** [comment]
Hi, the `hek293t_benchmark.tar.gz` is only processed from HEK293T-WT-rep1. But you can use the code `generate_rna_dataset.py
` to process all samples for hek293t_wt and hek293t_ko easily.

**Comment by wawpaopao** [comment]
thank you very much!
